export const CustomerDummy = {
  header: {
    request: '/api/customer/1',
    status: 'SUCCESS',
    status_code: 200,
    messages: [],
  },
  body: {
    hit_count: 1,
    data: [
      {
        id: 1,
        // sales_shop: '浅草橋店',
        sales_shop: 1,
        // sales_contact: '山田太郎',
        sales_contact: 1,
        name: '鈴木一郎',
        keisho: '様',
        furigana: 'スズキイチロウ',
        tel_no: '080-1111-2222',
        tel_no2: '080-1111-3333',
        tel_no3: '080-1111-4444',
        fax_no: '03-1111-2222',
        mail_address: 'xxx@aaa.com',
        mail_address2: 'xxx@bbb.com',
        mail_address3: 'xxx@ccc.com',
        post_no: '111-0053',
        prefecture: 13,
        city: '台東区',
        address: '浅草橋5-5-5',
        building_name: 'キムラビル4F',
        line_id: '12345',
        facebook_id: '67890',
        twitter_id: 'test',
        instagram_id: 'test2',
        // rank: 'プラチナ',
        rank: 1,
        // source: 'ホームページ',
        source: 1,
        estimated_rank: 'OB',
        area: 1,
        expected_part_list: [1, 3, 5],
        part_list: [1, 2, 3],
        building_category: 1,
        madori: 1,
        building_age: 1,
        remarks: '特になし',
        memo1: 'メモ1',
        memo2: 'メモ2',
        my_car_type: [1],
        my_car_type_other: 'test',
        tag_list: [1, 2, 3],
        introducer: '鈴木次郎',
        // wedding_anniversary: '2021-05-20',
        wedding_anniversary: '2021/05/20',
        lat: '35.70014287791868',
        lng: '139.78030639871204',
      },
    ],
  },
};
