export const SupportHistoryListDummy = {
  header: {
    request: '/api/support-history',
    status: 'SUCCESS',
    status_code: 200,
    messages: [],
  },
  body: {
    hit_count: 1,
    data: [
      {
        customer_id: 1,
        project_id: 1,
        id: 1,
        fixed_flag: true,
        reception_time: '2021/01/10 14:23:30',
        category: '契約内容',
        customer_name: '山田太郎',
        furigana: 'ヤマダタロウ',
        project_name: '山田太郎様宅メンテナンス',
        project_representative: '長谷川太郎',
        supported_person: '片岡竜',
        supported_complete_date: '2021/10/10',
        supported_history_name: '現場打ち合わせ',
      },
      {
        customer_id: 2,
        project_id: 2,
        id: 2,
        fixed_flag: true,
        reception_time: '2021/01/10 14:23:30',
        category: '契約内容',
        customer_name: '田中太郎',
        furigana: 'ヤマダタロウ',
        project_name: '田中太郎様宅メンテナンス',
        project_representative: '長谷川太郎',
        supported_person: '片岡竜',
        supported_complete_date: '2021/10/10',
        supported_history_name: '現場打ち合わせ',
      },
      {
        customer_id: 3,
        project_id: 3,
        id: 3,
        fixed_flag: true,
        reception_time: '2021/01/10 14:23:30',
        category: '契約内容',
        customer_name: '山本太郎',
        furigana: 'ヤマダタロウ',
        project_name: '山本太郎様宅メンテナンス',
        project_representative: '長谷川太郎',
        supported_person: '片岡竜',
        supported_complete_date: '2021/10/10',
        supported_history_name: '現場打ち合わせ',
      },
      {
        customer_id: 4,
        project_id: 4,
        id: 4,
        fixed_flag: true,
        reception_time: '2021/01/10 14:23:30',
        category: '契約内容',
        customer_name: '佐藤太郎',
        furigana: 'ヤマダタロウ',
        project_name: '佐藤太郎様宅メンテナンス',
        project_representative: '長谷川太郎',
        supported_person: '片岡竜',
        supported_complete_date: '2021/10/10',
        supported_history_name: '現場打ち合わせ',
      },

    ],
  },
};
