export const MasterStoreDummy = {
  header: {
    request: '/api/master/company/store',
    status: 'SUCCESS',
    status_code: 200,
    messages: [],
  },
  body: {
    hit_count: 2,
    data: [
      {
        id: 1,
        name: '店舗A',
        short_name: '店舗A',
        furigana: 'テンポエー',
        tel_no: '03-3865-5122',
        fax_no: '03-3865-5123',
        post_no: '123-4567',
        prefecture: '東京都',
        city: '台東区',
        address: '浅草橋5-5-5',
        building_name: '',
        valid_flag: true,
        free_dial: '0120-00-0000',
      },
      {
        id: 2,
        name: '店舗B',
        short_name: '店舗A',
        furigana: 'テンポエー',
        tel_no: '03-3865-5122',
        fax_no: '03-3865-5123',
        post_no: '123-4567',
        prefecture: '東京都',
        city: '台東区',
        address: '浅草橋5-5-5',
        building_name: '',
        valid_flag: true,
        free_dial: '0120-00-0000',
      },
      {
        id: 3,
        name: '店舗C',
        short_name: '店舗A',
        furigana: 'テンポエー',
        tel_no: '03-3865-5122',
        fax_no: '03-3865-5123',
        post_no: '123-4567',
        prefecture: '東京都',
        city: '台東区',
        address: '浅草橋5-5-5',
        building_name: '',
        valid_flag: true,
        free_dial: '0120-00-0000',
      },
    ],
  },
};
