export const MasterConstructionPartDummy = {
  header: {
    request: '/api/master/construction-part/',
    status: 'SUCCESS',
    status_code: 200,
    messages: [],
  },
  body: {
    hit_count: 2,
    data: [
      {
        construction_part_id: 1,
        id: '1',
        name: 'キッチン',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 2,
        id: '2',
        name: '浴室',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 3,
        id: '3',
        name: 'トイレ',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 4,
        id: '4',
        name: '洗面所',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 5,
        id: '5',
        name: '塗装',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 6,
        id: '6',
        name: '屋根',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 7,
        id: '7',
        name: '屋根',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 8,
        id: '8',
        name: '外壁',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 9,
        id: '9',
        name: '設備',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 10,
        id: '10',
        name: '増改築',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 11,
        id: '11',
        name: '改装',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 12,
        id: '12',
        name: '耐震',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 13,
        id: '13',
        name: 'エクステリア',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 14,
        id: '14',
        name: '内装',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 15,
        id: '15',
        name: 'バリアフリー',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 16,
        id: '16',
        name: 'メンテナンス',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 17,
        id: '17',
        name: '太陽光',
        input_flag: true,
        valid_flag: true,
      },
      {
        construction_part_id: 18,
        id: '18',
        name: 'その他',
        input_flag: true,
        valid_flag: true,
      },
    ],
  },
};
