export const MaintenanceDummy = {
  header: {
    request: '/api/maintenance/1',
    status: 'SUCCESS',
    status_code: 200,
    messages: [],
  },
  body: {
    hit_count: 1,
    data: [
      {
        customer_id: 1,
        project_id: 1,
        id: 1,
        customer_name: '山田太郎',
        furigana: 'ヤマダタロウ',
        title: '山田様3ヶ月後メンテ',
        post_no: '120-0043',
        customer_place: '東京都足立区千住宮元町２７－６',
        prefecture: 1,
        city: '足立区',
        address: '千住宮元町',
        building_name: '２７－６',
        customer_rank_name: 'SS',
        maintenance_past_flag: true,
        fixed_flag: true,
        tel_no: '03-1234-5678',
        project_representative: 1,
        maintenance_date: '2021/01/10',
        supported_date: '2021/01/10',
        project_name: '山田太郎様宅新築',
        sales_shop: 1,
        sales_contact: 1,
        field_name: '山田太郎様宅新築',
        construction_start_date: '2021/01/03',
        completion_end_date: '2021/05/03',
        construction_date: '2021/01/03',
        completion_date: '2021/01/30',

        contracted_date: '2021/01/15',
        detail: '詳細内容テスト',
        supported_content: '対応内容テスト',
      },
      {
        customer_id: 2,
        project_id: 2,
        id: 2,
        customer_name: '長谷川太郎',
        furigana: 'ハセガワタロウ',
        title: '長谷川様3ヶ月後メンテ',
        post_no: '120-0043',
        customer_place: '東京都足立区千住宮元町２７－６',
        prefecture: 1,
        city: '足立区',
        address: '千住宮元町',
        building_name: '２７－６',
        customer_rank_name: 'SS',
        maintenance_past_flag: true,
        fixed_flag: true,
        tel_no: '03-1234-5678',
        project_representative: 1,
        maintenance_date: '2021/01/10',
        supported_date: '2021/01/10',
        project_name: '長谷川太郎様宅新築',
        sales_shop: 1,
        sales_contact: 1,
        field_name: '長谷川太郎様宅新築',
        construction_start_date: '2021/01/03',
        completion_end_date: '2021/05/03',
        construction_date: '2021/01/03',
        completion_date: '2021/01/30',

        contracted_date: '2021/01/15',
        detail: '詳細内容テスト',
        supported_content: '対応内容テスト',
      },
    ],
  },
};
