export const FileListDummy = {
  header: {
    request: '/api/file',
    status: 'SUCCESS',
    status_code: 200,
    messages: [],
  },
  body: {
    hit_count: 1,
    data: [
      {
        customer_id: 1,
        project_id: 1,
        id: 1,
        no: 1,
        file_name: '原価管理表',
        format: 'xls',
        size: '23',
        upload_date: '2021/02/28 15:36:12',
        updater: '長谷川太郎',
        customer_name: '山田太郎',
        furigana: 'ヤマダタロウ',
        project_name: '山田太郎様宅新築',
        icon_thumbnail: '', // もしくはnull
        comment: '',
      },
      {
        customer_id: 2,
        project_id: 2,
        id: 2,
        no: 2,
        file_name: '原価管理表',
        format: 'jpg',
        size: '103',
        upload_date: '2021/02/28 15:36:12',
        updater: '木下次郎',
        customer_name: '山田太郎',
        furigana: 'ヤマダタロウ',
        project_name: '山田太郎様宅新築',
        icon_thumbnail: '', // もしくはnull
        comment: '',
      },
      {
        customer_id: 3,
        project_id: 3,
        id: 3,
        no: 3,
        file_name: '間取り画像',
        format: 'jpg',
        size: '500',
        upload_date: '2021/02/28 15:36:12',
        updater: '木下次郎',
        customer_name: '山田太郎',
        furigana: 'ヤマダタロウ',
        project_name: '山田太郎様宅新築',
        icon_thumbnail: '', // もしくはnull
        comment: '',
      },
      {
        customer_id: 4,
        project_id: 4,
        id: 4,
        no: 4,
        file_name: '外観画像',
        format: 'pdf',
        size: '200',
        upload_date: '2021/02/28 15:36:12',
        updater: '長谷川次郎',
        customer_name: '鈴木次郎',
        furigana: 'スズキジロウ',
        project_name: '鈴木次郎様宅新築',
        icon_thumbnail: '', // もしくはnull
        comment: '',
      },
      {
        customer_id: 5,
        project_id: 5,
        id: 5,
        no: 5,
        file_name: '素材管理表',
        format: 'xls',
        size: '105',
        upload_date: '2021/02/28 15:36:12',
        updater: '長谷川次郎',
        customer_name: '鈴木次郎',
        furigana: 'スズキジロウ',
        project_name: '鈴木次郎様宅新築',
        icon_thumbnail: '', // もしくはnull
        comment: '',
      },
    ],
  },
};
