export type MasterStore = {
  id: number,
  name: string,
  furigana: string,
  short_name: string,
  tel_no: string,
  fax_no: string,
  free_dial: string,
  post_no: string,
  prefecture: number,
  city: string,
  address: string,
  building_name: string,
  valid_flag: boolean,
  bank_name: string,
  bank_account_no: string,
  holder: string,
  bank_account: number,
  logo: Blob,
}
