import { TagModel } from '../../../../../model/tag/tag';

export type CustomerSort = Partial<{
  name: string,
  furigana: string,
  tel_no: string,
  tel_no2: string, /* TODO: 緊急連絡先のキー名の確認 */
  post_no1: string,
  post_no2: string,
  prefecture: number,
  address: string,
  rank: number,
  rank_filter: number,
  estimated_rank:number,
  estimated_rank_filter:number,
  area: number,
  sales_shop: number,
  sales_contact: number,
  customer_category: number, /* TODO: 顧客分類の有無・キー名の確認 */
  building_category: number,
  madori: number,
  building_age: number,
  building_age_filter: number, /* TODO: 築年数フィルターの有無・キー名の確認 */
  completion_start_year: number,
  completion_start_month: number,
  completion_end_year: number,
  completion_end_month: number,
  last_completion_start_year: number,
  last_completion_start_month: number,
  last_completion_end_year: number,
  last_completion_end_month: number,
  total_work_price_min: number,
  total_work_price_max: number,
  work_times_min: number,
  work_times_max: number,
  tags: TagModel | null,
  parts: TagModel | null,
  remarks: string,
  is_deficiency: boolean,
  north_lat: string,
  north_lng: string,
  south_lat: string,
  south_lng: string,
  offset: number,
  limit: number,
  sort_by: number,
  highlow: number,
}>
